# GDA Implementation.

Implement the Gaussian Discriminant Analysis (GDA) learning algorithm following the steps as discussed in class.

INSTRUCTION: Rename your notebook as: <br>
`firstName_LastName_Live_coding_GDA.ipynb`.

Notes: 
* Do not use any built-in functions to complete a task;
* Do not import additional libraries.

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import make_classification

In [2]:
# Generate data
def generate_data():
  x, y = make_classification(n_samples= 1000, n_features=3, n_redundant=0, 
                           n_informative=3, random_state=1, 
                           n_clusters_per_class=1)
  
  return x,y

x,y= generate_data()
# get data
print(x.shape, y.shape)

(1000, 3) (1000,)


In [3]:
x

array([[-0.42600458,  0.3092346 ,  1.13238592],
       [ 0.23750039,  0.85236655,  1.27032566],
       [-1.50956177,  0.57932947, -0.58204952],
       ...,
       [ 0.38796174,  1.01606996, -1.499496  ],
       [-0.74578403,  1.56454128, -1.05700466],
       [ 1.08716336, -0.29150009,  0.98548405]])

In [4]:
def split_data(x,y, train_size= 0.8):
    # shuffle the data to randomize the train/test split
  
    n = int(len(x)*train_size)
    indices = np.arange(len(x))
    np.random.shuffle(indices)
    train_idx = indices[: n]
    test_idx = indices[n:]
    X_train, y_train = x[train_idx], y[train_idx]
    X_test, y_test = x[test_idx], y[test_idx]
    return X_train,X_test,y_train,y_test

In [5]:
X_train, X_test, y_train, y_test= split_data(x,y, train_size=0.8) # split your data into x_train, x_test, y_train, y_test
print(X_train.shape, y_train.shape, X_test.shape, y_test.shape)

(800, 3) (800,) (200, 3) (200,)


In [6]:
#class
np.unique(y)

array([0, 1])

In [7]:
# for label in range(2):
#     bool_lean = (label==y)
# bool_lean

In [8]:
for lab in range(2):
    idx = np.where(y==lab,1,0)
idx[idx==0]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [9]:
#   def compute_mu(x,y,k):
#     d = x.shape[1]
#     self.mu = np.zeros((k,d))
#     for i in range(k):
#         idx = np.where(y==i)
#         x_trans = x[idx].T
#         for j in range(d):
#             self.mu[i,j]=np.mean(x_trans[j])
#     return self.mu

In [10]:
#   def compute_phi(self,x):
#         d =x.shape[1]
#         self.phi = np.zeros((d,1))
#         x_trans =x.T
#         for k in range(d):
#             self.phi[k]=np.mean(x_trans[k])
#         return self.phi

In [11]:
def covariance(x, mu):
    #mu.shape =(1,3) , x.shape =(m,3) for a single class
    m,d = x.shape
    cov =np.zeros((d,d))
    for i in range(d):
        for j in range(d):
            cov[i,j] = np.sum((x[:, i] - mu[i]) * (x[:, j] - mu[j])) / (m - 1)
    return cov
                

  # Easy way: cov= np.cov(x, rowvar=0) but do not use it. One can use it to assess his/her result.


In [12]:
# def covariance1(x, mu):
#     #mu.shape =(1,3) , x.shape =(m,3) for a single class
#     m,d = x.shape
#     sigma =np.zeros((d,d))
#     for i in range(d):
#         for j in range(d):
#             sigma[i, j] = np.sum((x[:, i] - mu[i] )* (x[:, j] - mu[j])) / (m - 1)
#     return sigma

In [13]:
np.cov(x,rowvar=0 )

array([[1.84495325, 0.02790646, 1.00137533],
       [0.02790646, 1.00170721, 0.05539176],
       [1.00137533, 0.05539176, 1.74832   ]])

In [54]:
covariance(x, x.mean(0))

array([[1.84495325, 0.02790646, 1.00137533],
       [0.02790646, 1.00170721, 0.05539176],
       [1.00137533, 0.05539176, 1.74832   ]])

In [44]:
class GDA:
  def __init__(self):
    ## set mu, phi and sigma to None
    self.mu = None
    self.phi = None
    self.sigma = None

  def fit(self,x,y):
    k= len(np.unique(y)) # Number of class.
    d=x.shape[1]  # input dim
    m= x.shape[0] # Number of examples.
    
    ## Initialize mu, phi and sigma
    self.mu=  np.zeros((k,d)) #: kxd, i.e., each row contains an individual class mu.
    self.phi = np.zeros(k) #k-dimension
    self.sigma= np.zeros((k,d,d))#: kxdxd, i.e., each row contains an individual class sigma.
    for lab in range(k):
        bool = (y==lab)
        self.mu[lab]=np.mean(x[bool],axis=0)
        self.phi[lab]=np.sum(bool)/m
        self.sigma[lab] = covariance(x[bool],self.mu[lab])
    

    print(f'mu = {self.mu}')
    print(f'phi = {self.phi}')
    print(f'sigma = {self.sigma}')
    return
    

  def predict_proba(self,x):
    # reshape or flatt x.
    d = x.shape[1]

    k_class= self.mu.shape[0] # Number of classes we have in our case it's k = 2

    ## START THE LEARNING: estimate mu, phi and sigma.
    proba = np.zeros((x.shape[0],k_class))
    for lab in range(k_class):
      p_y = self.phi[lab]
      for i in range(x.shape[0]):
        proba[i,lab]=1/((2*np.pi)**(d/2)*np.linalg.det(self.sigma[lab])**0.5)*np.exp(-0.5*(x[i]-self.mu[lab]).T@np.linalg.inv(self.sigma[lab])@(x[i]-self.mu[lab]))*p_y
        
    return proba
  
  def predict(self,x):
    probx = self.predict_proba(x)
    y_pred = np.argmax(probx, axis=1)
    return y_pred
    
  def accuracy(self, y, ypreds):
        accur = np.mean(y==ypreds)*100
        return accur
    

In [45]:
model= GDA()
model.fit(X_train,y_train)

mu = [[ 1.00654398  1.04354037  0.99587741]
 [-1.03527687  0.95189276 -0.92804407]]
phi = [0.5025 0.4975]
sigma = [[[ 0.85564658 -0.41380969 -0.06320862]
  [-0.41380969  1.71295818  0.10354969]
  [-0.06320862  0.10354969  0.03829065]]

 [[ 0.75946304  0.34944637  0.0828407 ]
  [ 0.34944637  0.33045824 -0.07067382]
  [ 0.0828407  -0.07067382  1.55162675]]]


In [46]:
yproba= model.predict_proba(X_test)
yproba

array([[3.32058888e-012, 4.99541532e-002],
       [9.22017940e-002, 6.26793273e-007],
       [3.00632226e-047, 5.54940381e-002],
       [3.31658338e-138, 8.08474933e-004],
       [3.25672471e-012, 3.67130184e-002],
       [2.80588292e-002, 5.91165823e-007],
       [2.44746494e-017, 6.01661712e-002],
       [1.05281303e-001, 7.05863596e-006],
       [6.80658530e-002, 1.34229429e-002],
       [2.73633283e-004, 1.41357324e-002],
       [1.43681508e-057, 3.61004894e-003],
       [6.73219488e-030, 1.60148672e-002],
       [9.22217111e-003, 2.39011138e-002],
       [1.01678199e-001, 3.39228512e-006],
       [3.10702225e-002, 3.41743193e-009],
       [3.71855444e-003, 2.11365318e-002],
       [4.77539198e-003, 1.38406778e-020],
       [1.49420104e-026, 4.89404538e-002],
       [4.67235323e-003, 2.17842156e-007],
       [1.48692303e-001, 2.64038467e-004],
       [5.73284480e-015, 7.23008389e-003],
       [1.52223789e-005, 1.09589092e-003],
       [4.34936328e-002, 2.21888935e-004],
       [1.4

In [47]:
ypreds= model.predict(X_test)
ypreds


array([1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0,
       1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0,
       1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 0])

In [48]:
model.accuracy(y_test, ypreds)

96.5

# Logistic Regression

In [49]:
class LogisticRegression:
  '''
  The goal of this class is to create a LogisticRegression class, 
  that we will use as our model to classify data point into a corresponding class
  '''
  def __init__(self,lr,n_epochs):
    self.lr = lr
    self.n_epochs = n_epochs
    self.train_losses = []
    self.w = None
    self.weight = []

  def add_ones(self, x):
    ##### WRITE YOUR CODE HERE #####
    one = np.ones(len(x)).reshape(-1,1)
    return np.hstack((one,x))
    
    #### END CODE ####

  def sigmoid(self, x):
    ##### WRITE YOUR CODE HERE ####
    sigmo = 1/(1+np.exp(-x@self.w))
    return sigmo
    #### END CODE ####

  def cross_entropy(self, x, y_true):
    ##### WRITE YOUR CODE HERE #####
    y_pred = self.sigmoid(x)
    loss = -np.mean((y_true*np.log(y_pred)+(1.0-y_true)*np.log(1-y_pred)))
    return loss
    #### END CODE ####
  
  def predict_proba(self,x):  #This function will use the sigmoid function to compute the probalities
    ##### WRITE YOUR CODE HERE #####
    x= self.add_ones(x)
    proba = self.sigmoid(x)
    return proba
    #### END CODE ####

  def predict(self,x):
    ##### WRITE YOUR CODE HERE #####
    probas = self.predict_proba(x)
    output = np.where(probas>0.5,1,0)      #convert the probalities into 0 and 1 by using a treshold=0.5
    return output
    #### END CODE ####

  def fit(self,x,y):
    # Add ones to x
    x =self.add_ones(x)
    

    # reshape y if needed
    y = y.reshape(-1,1)

    
    # Initialize w to zeros vector >>> (x.shape[1])
    self.w = np.zeros((x.shape[1],1))

    for epoch in range(self.n_epochs):
      # make predictions
      ypred = self.sigmoid(x)

      #compute the gradient
      dl = (x.T@(y-ypred))*(-1/x.shape[0])

      #update rule
      self.w = self.w-self.lr*dl


      #Compute and append the training loss in a list
      loss = self.cross_entropy(x,y)
      self.train_losses.append(loss)

      if epoch%100 == 0:
        print(f'loss for epoch {epoch}  : {loss}')

  def accuracy(self,y_true, y_pred):
    ##### WRITE YOUR CODE HERE #####
    acc = np.mean(y_true==y_pred)*100
    return acc
    #### END CODE ####

In [50]:
model1 = LogisticRegression(0.01,n_epochs=1000)
model1.fit(X_train,y_train)

loss for epoch 0  : 0.6882382647610037
loss for epoch 100  : 0.41648130417812845
loss for epoch 200  : 0.3214456917467037
loss for epoch 300  : 0.2747391788259215
loss for epoch 400  : 0.24699732872357452
loss for epoch 500  : 0.2285716883719762
loss for epoch 600  : 0.2154126829830797
loss for epoch 700  : 0.20552685830681564
loss for epoch 800  : 0.19781810590243792
loss for epoch 900  : 0.1916329079274979


In [51]:
X_test

array([[-1.29069742e+00,  6.42641320e-01, -2.55367792e-02],
       [ 1.88932910e+00,  8.88407903e-01,  1.01384501e+00],
       [-1.04358775e+00,  7.28855860e-01, -1.39707406e+00],
       [-3.27492914e+00,  6.05359482e-02, -3.09156465e+00],
       [-1.77114790e-01,  1.18890804e+00, -1.32991549e-01],
       [ 7.35251114e-01, -2.18754749e-02,  1.23083719e+00],
       [-6.73051461e-01,  1.02315810e+00, -3.62395828e-01],
       [ 1.77767229e+00,  1.11080409e+00,  9.27984665e-01],
       [-1.61581011e-01,  1.38064779e+00,  1.01612181e+00],
       [-1.33640522e+00,  1.16287617e+00,  7.07009811e-01],
       [-2.95114755e+00,  5.14632620e-01, -1.49418386e+00],
       [-2.07110023e+00, -4.66233841e-02, -7.63564661e-01],
       [-4.17671691e-01,  1.14084243e+00,  7.65824438e-01],
       [ 1.81877815e+00,  1.04691742e+00,  9.94656849e-01],
       [ 1.05658735e+00, -2.64375882e-01,  6.72569302e-01],
       [-8.74151489e-01,  1.20225918e+00,  7.96206096e-01],
       [ 1.25179648e+00, -1.65968431e+00

In [52]:
ypreds= model1.predict(X_test)
ypreds

array([[1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
    

In [53]:
model.accuracy(y_test, ypreds.flatten())

92.0